name: Deploy Research Flowstream Backend to Hugging Face Spaces

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Space payload
        run: |
          rm -rf space_backend && mkdir -p space_backend
          # Copy backend folder
          rsync -av --exclude '__pycache__' --exclude '.DS_Store' backend/ space_backend/backend/

          # Add README.md for Space
          cat > space_backend/README.md << 'EOF'
          ---
          title: Research Flowstream (Backend)
          sdk: docker
          ---
          EOF

          # Create Dockerfile
          cat > space_backend/Dockerfile << 'EOF'
          FROM python:3.10-slim
          WORKDIR /app
          ENV HF_HOME=/app/.cache
          ENV TRANSFORMERS_CACHE=/app/.cache
          ENV TORCH_HOME=/app/.cache
          ENV PORT=7860
          COPY backend/ /app/backend/
          COPY backend/requirements.txt /app/backend/requirements.txt
          RUN pip install --no-cache-dir -r /app/backend/requirements.txt
          CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "7860"]
          EOF

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          cd space_backend
          git init
          git branch -M main
          git lfs install
          git remote add origin https://Jayanthk2004:${HF_TOKEN}@huggingface.co/spaces/Jayanthk2004/Research-Flowstream
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy backend from GitHub Actions"
          git push -u origin main --force
